// Objective-C API for talking to github.com/ibigbug/CameraAPI Go package.
//   gobind -lang=objc github.com/ibigbug/CameraAPI
//
// File is generated by gobind. Do not edit.

#ifndef __CameraAPI_H__
#define __CameraAPI_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class CameraAPIDeviceDescription;
@class CameraAPIDeviceDescriptionXML;
@class CameraAPIRPCRequest;
@class CameraAPIRPCResponse;

@interface CameraAPIDeviceDescription : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull guideUrl;
@property (nonatomic) NSString* _Nonnull systemUrl;
@property (nonatomic) NSString* _Nonnull accessControlUrl;
@property (nonatomic) NSString* _Nonnull cameraUrl;
@end

@interface CameraAPIDeviceDescriptionXML : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field DeviceDescriptionXML.XMLName with unsupported type: encoding/xml.Name

@property (nonatomic) NSString* _Nonnull text;
@property (nonatomic) NSString* _Nonnull xmlns;
@property (nonatomic) NSString* _Nonnull dlna;
@property (nonatomic) NSString* _Nonnull av;
// skipped field DeviceDescriptionXML.SpecVersion with unsupported type: struct{Text string "xml:\",chardata\""; Major string "xml:\"major\""; Minor string "xml:\"minor\""}

// skipped field DeviceDescriptionXML.Device with unsupported type: struct{Text string "xml:\",chardata\""; DeviceType string "xml:\"deviceType\""; FriendlyName string "xml:\"friendlyName\""; Manufacturer string "xml:\"manufacturer\""; ManufacturerURL string "xml:\"manufacturerURL\""; ModelDescription string "xml:\"modelDescription\""; ModelName string "xml:\"modelName\""; ModelURL string "xml:\"modelURL\""; UDN string "xml:\"UDN\""; ServiceList struct{Text string "xml:\",chardata\""; Service []struct{Text string "xml:\",chardata\""; ServiceType string "xml:\"serviceType\""; ServiceId string "xml:\"serviceId\""; SCPDURL string "xml:\"SCPDURL\""; ControlURL string "xml:\"controlURL\""; EventSubURL string "xml:\"eventSubURL\""} "xml:\"service\""} "xml:\"serviceList\""; XScalarWebAPIDeviceInfo struct{Text string "xml:\",chardata\""; Av string "xml:\"av,attr\""; XScalarWebAPIVersion string "xml:\"X_ScalarWebAPI_Version\""; XScalarWebAPIServiceList struct{Text string "xml:\",chardata\""; XScalarWebAPIService []struct{Text string "xml:\",chardata\""; XScalarWebAPIServiceType string "xml:\"X_ScalarWebAPI_ServiceType\""; XScalarWebAPIActionListURL string "xml:\"X_ScalarWebAPI_ActionList_URL\""; XScalarWebAPIAccessType string "xml:\"X_ScalarWebAPI_AccessType\""} "xml:\"X_ScalarWebAPI_Service\""} "xml:\"X_ScalarWebAPI_ServiceList\""; XScalarWebAPIImagingDevice struct{Text string "xml:\",chardata\""; XScalarWebAPILiveViewURL string "xml:\"X_ScalarWebAPI_LiveView_URL\""; XScalarWebAPIDefaultFunction string "xml:\"X_ScalarWebAPI_DefaultFunction\""} "xml:\"X_ScalarWebAPI_ImagingDevice\""} "xml:\"X_ScalarWebAPI_DeviceInfo\""}

@end

@interface CameraAPIRPCRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull method;
// skipped field RPCRequest.Params with unsupported type: []string

@property (nonatomic) long id_;
@property (nonatomic) NSString* _Nonnull version;
@end

@interface CameraAPIRPCResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long id_;
// skipped field RPCResponse.Result with unsupported type: []interface{}

// skipped field RPCResponse.Error with unsupported type: []interface{}

@end

FOUNDATION_EXPORT NSString* _Nonnull const CameraAPIBroadcastAddr;
FOUNDATION_EXPORT NSString* _Nonnull const CameraAPIHOST;
FOUNDATION_EXPORT NSString* _Nonnull const CameraAPIMAN;
FOUNDATION_EXPORT NSString* _Nonnull const CameraAPIMX;
FOUNDATION_EXPORT NSString* _Nonnull const CameraAPIRequestLine;
FOUNDATION_EXPORT NSString* _Nonnull const CameraAPIST;
FOUNDATION_EXPORT NSString* _Nonnull const CameraAPIUSER_AGENT;

FOUNDATION_EXPORT NSString* _Nonnull CameraAPICameraDiscovery(void);

FOUNDATION_EXPORT CameraAPIDeviceDescription* _Nullable CameraAPIGetDeviceDescription(NSString* _Nullable cameraAddr);

#endif
