
// Objective-C API for talking to the following Go packages
//
//	github.com/ibigbug/CameraAPI
//
// File is generated by gomobile bind. Do not edit.
#ifndef __CameraAPI_FRAMEWORK_H__
#define __CameraAPI_FRAMEWORK_H__

#include "CameraAPI.objc.h"
#include "Universe.objc.h"

#endif
